# Generated by Django 4.2.16 on 2024-11-20 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_user_group_alter_user_school_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
