# Generated by Django 4.2.16 on 2024-11-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_lesson_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('MA', 'Math'), ('IT', 'Information technology'), ('EN', 'English'), ('BL', 'Biology'), ('CH', 'Chemistry'), ('PH', 'Physics'), ('GE', 'Geography'), ('HI', 'History')], max_length=20),
        ),
    ]
