# Generated by Django 4.2.16 on 2024-11-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_remove_lesson_group_lesson_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_lessons', to='classroom.class'),
            preserve_default=False,
        ),
    ]
