# Generated by Django 4.2.16 on 2025-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_remove_lesson_students_lesson_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_homeworks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
