# Generated by Django 4.2.16 on 2025-05-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_homework_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('feedback', models.CharField(max_length=1000)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='classroom.homework_submission')),
            ],
        ),
    ]
